# Generated by Django 4.2 on 2023-04-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id_usuario',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nome',
            new_name='username',
        ),
    ]
